### ISSUE TITLE
Regression testing for meta-rdk-belvedere

### ISSUE THREAD

**Issue by srinib1982** [belvedere-yocto/meta-rdk-belvedere#9]
Hi-
I have recently started working on RDK and came across this meta layer which works for rpi hardware. This is helpfull. I am able to follow the steps and bring up the image on rpi hardware. 

Now I wanted to know a way to verify and thinking if any regression or test suite available and if so, possible to point it out?

Thanks for fixing the remove_cosa_sim bug as I hit on that and did similar changes yesterday to fix the build error. 

Thanks,
Srini

**Comment by s-maynard** [comment]
This code has been consumed into RDK and will be available on CMF.  Once it is available this repo will be going away - please don't base any projects on it...
